# **COBIFY**

## **Import libraries**

In [1]:
import pandas as pd
import numpy as np

## **Clean and transform**

In [2]:
# load data
measurements = pd.read_csv('../data/measurements.csv')

measurements2 = pd.read_excel('../data/measurements2.xlsx')

In [3]:
measurements.head()

distance consume  speed temp_inside  temp_outside specials gas_type  AC  \
0       28       5     26        21,5            12      NaN      E10   0   
1       12     4,2     30        21,5            13      NaN      E10   0   
2     11,2     5,5     38        21,5            15      NaN      E10   0   
3     12,9     3,9     36        21,5            14      NaN      E10   0   
4     18,5     4,5     46        21,5            15      NaN      E10   0   

   rain  sun refill liters refill gas  
0     0    0            45        E10  
1     0    0           NaN        NaN  
2     0    0           NaN        NaN  
3     0    0           NaN        NaN  
4     0    0           NaN        NaN

In [4]:
measurements2.head()

distance  consume  speed  temp_inside  temp_outside specials gas_type  AC  \
0      28.0      5.0     26         21.5            12      NaN      E10   0   
1      12.0      4.2     30         21.5            13      NaN      E10   0   
2      11.2      5.5     38         21.5            15      NaN      E10   0   
3      12.9      3.9     36         21.5            14      NaN      E10   0   
4      18.5      4.5     46         21.5            15      NaN      E10   0   

   rain  sun  refill liters refill gas  
0     0    0           45.0        E10  
1     0    0            NaN        NaN  
2     0    0            NaN        NaN  
3     0    0            NaN        NaN  
4     0    0            NaN        NaN

In [5]:
measurements.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   distance       388 non-null    object
 1   consume        388 non-null    object
 2   speed          388 non-null    int64 
 3   temp_inside    376 non-null    object
 4   temp_outside   388 non-null    int64 
 5   specials       93 non-null     object
 6   gas_type       388 non-null    object
 7   AC             388 non-null    int64 
 8   rain           388 non-null    int64 
 9   sun            388 non-null    int64 
 10  refill liters  13 non-null     object
 11  refill gas     13 non-null     object
dtypes: int64(5), object(7)
memory usage: 36.5+ KB


In [6]:
measurements2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   distance       388 non-null    float64
 1   consume        388 non-null    float64
 2   speed          388 non-null    int64  
 3   temp_inside    376 non-null    float64
 4   temp_outside   388 non-null    int64  
 5   specials       93 non-null     object 
 6   gas_type       388 non-null    object 
 7   AC             388 non-null    int64  
 8   rain           388 non-null    int64  
 9   sun            388 non-null    int64  
 10  refill liters  13 non-null     float64
 11  refill gas     13 non-null     object 
dtypes: float64(4), int64(5), object(3)
memory usage: 36.5+ KB


### **"Measurements"**

In [7]:
# cols
measurements.columns

Index(['distance', 'consume', 'speed', 'temp_inside', 'temp_outside',
       'specials', 'gas_type', 'AC', 'rain', 'sun', 'refill liters',
       'refill gas'],
      dtype='object')

In [8]:
# "distance" unique values
measurements.distance.unique()

array(['28', '12', '11,2', '12,9', '18,5', '8,3', '7,8', '12,3', '4,9',
       '11,9', '12,4', '11,8', '24,7', '17,3', '33,4', '25,9', '25,3',
       '14,2', '17,9', '18,4', '18,3', '32,6', '19', '12,1', '20', '4,5',
       '11,7', '10,2', '5,4', '2', '16', '27,3', '10,6', '11,6', '13,1',
       '6,1', '153,5', '2,9', '2,1', '9,8', '6,8', '14', '13,9', '9,7',
       '24,8', '34,8', '5,2', '10,5', '13,2', '13', '12,2', '12,5',
       '15,7', '6,4', '5,3', '26,2', '18,8', '22,9', '162,7', '16,6',
       '15,9', '5,1', '22,4', '31,1', '16,1', '4,2', '17,4', '23,5', '7',
       '20,1', '20,8', '1,7', '35,9', '36,9', '16,8', '9,9', '36,6',
       '44,9', '21,6', '39,4', '26,6', '53,2', '18,9', '43,5', '16,4',
       '21,1', '22,7', '44,4', '35,8', '40,6', '14,1', '58,7', '16,2',
       '31,8', '51,6', '38,6', '81,2', '130,3', '67,2', '43,7', '56,1',
       '39', '38,5', '28,2', '19,6', '22,2', '13,6', '12,6', '8,7', '7,9',
       '2,4', '18,1', '1,3', '13,4', '12,8', '29', '31,4', '27,1', '

In [9]:
# convert "string" to "float"
measurements.distance = measurements.distance.str.replace(',', '.').astype(float)

measurements.distance.info()

<class 'pandas.core.series.Series'>
RangeIndex: 388 entries, 0 to 387
Series name: distance
Non-Null Count  Dtype  
--------------  -----  
388 non-null    float64
dtypes: float64(1)
memory usage: 3.2 KB


In [10]:
# "consume" unique values
measurements.consume.unique()

array(['5', '4,2', '5,5', '3,9', '4,5', '6,4', '4,4', '5,3', '5,6', '4,6',
       '5,9', '5,1', '4,7', '4,9', '5,7', '4,1', '5,8', '4,8', '4,3',
       '5,2', '7,4', '6,5', '4', '3,3', '9,9', '6,1', '6,2', '7,9',
       '12,2', '5,4', '3,6', '6,9', '8,7', '6,3', '6', '10,8', '8,1',
       '7,1', '3,8', '9', '3,7', '11,5', '6,6'], dtype=object)

In [11]:
# convert "string" to "float"
measurements.consume = measurements.consume.str.replace(',', '.').astype(float)

measurements.consume.info()

<class 'pandas.core.series.Series'>
RangeIndex: 388 entries, 0 to 387
Series name: consume
Non-Null Count  Dtype  
--------------  -----  
388 non-null    float64
dtypes: float64(1)
memory usage: 3.2 KB


In [12]:
# "speed" unique values
measurements.speed.unique()

array([26, 30, 38, 36, 46, 50, 43, 40, 42, 59, 58, 24, 32, 39, 37, 62, 57,
       21, 28, 29, 35, 51, 23, 55, 44, 25, 63, 61, 82, 52, 18, 41, 20, 56,
       45, 22, 60, 33, 34, 71, 75, 66, 27, 49, 14, 80, 53, 47, 73, 69, 85,
       67, 54, 31, 48, 16, 88, 65, 90, 87])

In [13]:
# "temp_inside" unique values
measurements.temp_inside.unique()

array(['21,5', '22,5', '20', nan, '21', '20,5', '23', '23,5', '25', '24',
       '22', '19', '24,5', '25,5'], dtype=object)

In [26]:
# convert "nan" values to "unknown"
measurements.temp_inside = measurements.temp_inside.fillna('unknown')

# convert "string"
measurements.temp_inside = measurements.temp_inside.str.replace(',', '.')

measurements.temp_inside.unique()

array(['21.5', '22.5', '20', 'unknown', '21', '20.5', '23', '23.5', '25',
       '24', '22', '19', '24.5', '25.5'], dtype=object)

In [15]:
# "temp_outside" unique values
measurements.temp_outside.unique()

array([12, 13, 15, 14, 10, 11,  6,  4,  9,  0,  5,  3,  8,  1,  2,  7, -3,
       17, 18, -5, 16, 19, 21, 20, 25, 23, 27, 24, 26, 22, 30, 31, 28])

In [16]:
# "specials" unique values
measurements.specials.unique()

array([nan, 'AC rain', 'AC', 'rain', 'snow', 'AC snow',
       'half rain half sun', 'sun', 'AC sun', 'sun ac', 'ac', 'AC Sun',
       'ac rain'], dtype=object)

In [18]:
# "specials" column drop
measurements = measurements.drop('specials', axis=1)

measurements.columns

Index(['distance', 'consume', 'speed', 'temp_inside', 'temp_outside',
       'gas_type', 'AC', 'rain', 'sun', 'refill liters', 'refill gas'],
      dtype='object')

In [19]:
# "gas_type" unique values
measurements.gas_type.unique()

array(['E10', 'SP98'], dtype=object)

In [20]:
# "AC" unique values
measurements.AC.unique()

array([0, 1])

In [21]:
# "rain" unique values
measurements.rain.unique()

array([0, 1])

In [22]:
# "sun" unique values
measurements.sun.unique()

array([0, 1])

In [23]:
# "refill liters" change name to "refill_liters"
measurements = measurements.rename(columns={'refill liters': 'refill_liters'})

measurements.columns

Index(['distance', 'consume', 'speed', 'temp_inside', 'temp_outside',
       'gas_type', 'AC', 'rain', 'sun', 'refill_liters', 'refill gas'],
      dtype='object')

In [24]:
# "refill_liters" unique values
measurements.refill_liters.unique()

array(['45', nan, '37,6', '37,7', '38', '38,3', '10', '39', '41', '37',
       '37,2'], dtype=object)

In [27]:
# convert "nan" values to "unknown"
measurements.refill_liters = measurements.refill_liters.fillna('unknown')

# convert "string"
measurements.refill_liters = measurements.refill_liters.str.replace(',', '.')

measurements.refill_liters.unique()

array(['45', 'unknown', '37.6', '37.7', '38', '38.3', '10', '39', '41',
       '37', '37.2'], dtype=object)

In [28]:
# "refill gas" change name to "refill_gas"
measurements = measurements.rename(columns={'refill gas': 'refill_gas'})

measurements.columns

Index(['distance', 'consume', 'speed', 'temp_inside', 'temp_outside',
       'gas_type', 'AC', 'rain', 'sun', 'refill_liters', 'refill_gas'],
      dtype='object')

In [29]:
# "refill_gas" unique values
measurements.refill_gas.unique()

array(['E10', nan, 'SP98'], dtype=object)

In [30]:
# convert "nan" values to "unknown"
measurements.refill_gas = measurements.refill_gas.fillna('unknown')

measurements.refill_gas.unique()

array(['E10', 'unknown', 'SP98'], dtype=object)